# Generated by Django 5.2.17 on 2026-08-22 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingCoreLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=64)),
                ('contract_id', models.CharField(max_length=64)),
                ('subscription_id', models.CharField(max_length=64)),
                ('plan_version_id', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_core_link', to='accounts.organization')),
            ],
        ),
    ]
