# Generated by Django 5.2.17 on 2026-08-22 11:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('work', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('action', models.CharField(choices=[('assign', 'Assign a member'), ('add_label', 'Add a label'), ('notify_creator', 'Notify the task creator')], max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('add_label', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='work.label')),
                ('assign_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='work.project')),
                ('trigger_column', models.ForeignKey(help_text='fires when a task is moved into this column', on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='work.column')),
            ],
        ),
        migrations.CreateModel(
            name='AutomationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='succeeded', max_length=12)),
                ('detail', models.CharField(blank=True, max_length=200)),
                ('ran_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_runs', to='accounts.organization')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='work.task')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='automation.rule')),
            ],
            options={
                'ordering': ['-ran_at'],
            },
        ),
    ]
