defmodule BillingCore.Domain.Period do
  @moduledoc """
  Half-open date periods `[start_date, end_date_exclusive)` (SPEC INV-007, §9.2).

  Properties:

    * `start_date < end_date_exclusive`;
    * day count is `end_date_exclusive - start_date`;
    * adjacent periods `[A, B)` / `[B, C)` do not overlap;
    * ERP adapters convert to inclusive dates (`end_date_exclusive - 1 day`) at
      the adapter boundary only.
  """

  alias Decimal, as: D

  @enforce_keys [:start_date, :end_date_exclusive]
  defstruct [:start_date, :end_date_exclusive]

  @type t :: %__MODULE__{start_date: Date.t(), end_date_exclusive: Date.t()}

  @spec new!(Date.t(), Date.t()) :: t()
  def new!(%Date{} = start_date, %Date{} = end_date_exclusive) do
    unless Date.before?(start_date, end_date_exclusive) do
      raise ArgumentError,
            "period start #{start_date} must be before exclusive end #{end_date_exclusive}"
    end

    %__MODULE__{start_date: start_date, end_date_exclusive: end_date_exclusive}
  end

  @spec new(Date.t(), Date.t()) :: {:ok, t()} | {:error, :invalid_period}
  def new(%Date{} = start_date, %Date{} = end_date_exclusive) do
    if Date.before?(start_date, end_date_exclusive) do
      {:ok, %__MODULE__{start_date: start_date, end_date_exclusive: end_date_exclusive}}
    else
      {:error, :invalid_period}
    end
  end

  @doc "Number of service days in the period."
  @spec days(t()) :: pos_integer()
  def days(%__MODULE__{} = p), do: Date.diff(p.end_date_exclusive, p.start_date)

  @doc "Inclusive end date used by ERP adapters: `end_date_exclusive - 1 day`."
  @spec inclusive_end(t()) :: Date.t()
  def inclusive_end(%__MODULE__{} = p), do: Date.add(p.end_date_exclusive, -1)

  @spec contains_date?(t(), Date.t()) :: boolean()
  def contains_date?(%__MODULE__{} = p, %Date{} = date) do
    not Date.before?(date, p.start_date) and Date.before?(date, p.end_date_exclusive)
  end

  @spec covers?(t(), t()) :: boolean()
  def covers?(%__MODULE__{} = outer, %__MODULE__{} = inner) do
    not Date.before?(inner.start_date, outer.start_date) and
      not Date.after?(inner.end_date_exclusive, outer.end_date_exclusive)
  end

  @spec overlaps?(t(), t()) :: boolean()
  def overlaps?(%__MODULE__{} = a, %__MODULE__{} = b) do
    Date.before?(a.start_date, b.end_date_exclusive) and
      Date.before?(b.start_date, a.end_date_exclusive)
  end

  @doc "Intersection of two periods, or `nil` when they do not overlap."
  @spec intersect(t(), t()) :: t() | nil
  def intersect(%__MODULE__{} = a, %__MODULE__{} = b) do
    start_date = Enum.max([a.start_date, b.start_date], Date)
    end_date = Enum.min([a.end_date_exclusive, b.end_date_exclusive], Date)

    if Date.before?(start_date, end_date) do
      %__MODULE__{start_date: start_date, end_date_exclusive: end_date}
    end
  end

  @spec adjacent?(t(), t()) :: boolean()
  def adjacent?(%__MODULE__{} = a, %__MODULE__{} = b) do
    a.end_date_exclusive == b.start_date or b.end_date_exclusive == a.start_date
  end

  @doc """
  Exact proration fraction `active_days / period_days` as a `Decimal`
  (SPEC §10.1). The active period must be contained in the full period.
  """
  @spec proration_fraction(t(), t()) :: D.t()
  def proration_fraction(%__MODULE__{} = full, %__MODULE__{} = active) do
    unless covers?(full, active) do
      raise ArgumentError,
            "active period #{inspect(active)} must be contained in #{inspect(full)}"
    end

    D.div(D.new(days(active)), D.new(days(full)))
  end

  @doc """
  Adds `months` to `date`, clamping the day to the last valid day of the target
  month (Jan 31 + 1 month → Feb 28/29; SPEC BC-US-065). The intended anchor day
  must be supplied separately so repeated stepping does not lose it
  (Jan 31 → Feb 28 → Mar 31, not Mar 28).
  """
  @spec add_months(Date.t(), integer(), pos_integer()) :: Date.t()
  def add_months(%Date{} = date, months, anchor_day)
      when is_integer(months) and anchor_day in 1..31 do
    total = date.year * 12 + (date.month - 1) + months
    year = div(total, 12)
    month = rem(total, 12) + 1
    day = min(anchor_day, :calendar.last_day_of_the_month(year, month))
    Date.new!(year, month, day)
  end

  @doc """
  The billing period containing or starting at `from`, for a subscription
  anchored at `anchor_day` with a whole-month interval of `interval_months`,
  counted from `subscription_start`. Periods are generated by stepping months
  from the subscription start so anchors stay stable across clamped months.
  """
  @spec billing_period_at(Date.t(), Date.t(), pos_integer()) :: t()
  def billing_period_at(%Date{} = subscription_start, %Date{} = from, interval_months)
      when interval_months in [1, 2, 3, 4, 6, 12] do
    anchor_day = subscription_start.day

    n = month_steps_between(subscription_start, from, interval_months, anchor_day)

    start_date = add_months(subscription_start, n * interval_months, anchor_day)
    end_date = add_months(subscription_start, (n + 1) * interval_months, anchor_day)
    new!(start_date, end_date)
  end

  defp month_steps_between(sub_start, from, interval_months, anchor_day) do
    approx =
      div(
        from.year * 12 + from.month - (sub_start.year * 12 + sub_start.month),
        interval_months
      )

    # The month-count approximation can be off by one around clamped anchors;
    # walk to the step whose period contains `from`.
    Enum.find((approx - 1)..(approx + 1), approx, fn n ->
      s = add_months(sub_start, n * interval_months, anchor_day)
      e = add_months(sub_start, (n + 1) * interval_months, anchor_day)
      n >= 0 and not Date.before?(from, s) and Date.before?(from, e)
    end)
  end
end
